//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistarUtilizador
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilizadorA
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Apelido { get; set; }
        public string Sexo { get; set; }
        public string Morada { get; set; }
        public string CodP { get; set; }
        public string Localidade { get; set; }
        public string Telefone { get; set; }
        public string DataNasc { get; set; }
        public string CC { get; set; }
        public string EstadoC { get; set; }
        public string Perfil { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
