//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mds
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string BICC { get; set; }
        public string DataNascimento { get; set; }
        public string NSNS { get; set; }
        public string Morada { get; set; }
        public string NIF { get; set; }
        public string Sexo { get; set; }
        public string EstCivil { get; set; }
        public string Contacto { get; set; }
    }
}
