//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseDeDadosPrototipoContainer : DbContext
    {
        public BaseDeDadosPrototipoContainer()
            : base("name=BaseDeDadosPrototipoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultas> ConsultasSet { get; set; }
        public virtual DbSet<Medicacao> MedicacaoSet { get; set; }
        public virtual DbSet<Pacientes> PacientesSet { get; set; }
    }
}
