//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultas()
        {
            this.Medicacao = new HashSet<Medicacao>();
        }
    
        public int IdConsulta { get; set; }
        public System.DateTime DataDeRealizacao { get; set; }
        public string DoutorResponsavel { get; set; }
        public string Exames { get; set; }
        public int PacientesIdPaciente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicacao> Medicacao { get; set; }
        public virtual Pacientes Pacientes { get; set; }

        public override string ToString()
        {
            return IdConsulta + " | " + DataDeRealizacao.ToShortDateString() + " | " + DoutorResponsavel;
        }
    }
}
