//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicacao
    {
        public int IdMedicacao { get; set; }
        public string Nome { get; set; }
        public int Quantidade { get; set; }
        public int ConsultasIdConsulta { get; set; }
    
        public virtual Consultas Consultas { get; set; }
    }
}
